import { TopicComments } from "@/types/TopicComments";

export const OPPORTUNITIES_DATASET: TopicComments[] = [
  {
    ID: 1,
    received: "16-02-2024",
    module: "Decarbonising for net zero",
    idea: "Decarbonising for net zero",
    description: "good knowledge",
    label: null,
    country: "Sweden",
    category: "Content",
    comments_eng: "good knowledge",
    subtopic_relevance: "relevant",
    subtopic: "Knowledge Sharing",
  },
  {
    ID: 2,
    received: "16-02-2024",
    module: "Introduction to Artificial Intelligence",
    idea: "Introduction to Artificial Intelligence",
    description:
      "If we shall success with AI in Ramboll it's Important that employees are educated in AI.",
    label: "Tools: Internal database for Projects/Materials",
    country: "Denmark",
    category: "Content",
    comments_eng:
      "If we shall success with AI in Ramboll it's Important that employees are educated in AI.",
    subtopic_relevance: "relevant",
    subtopic: "AI Implementation",
  },
  {
    ID: 3,
    received: "14-02-2024",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description:
      "I would like to learn how someone who is not involved in the sustainability team can make big strides in sustainability. I would also like to know how I can do this as a junior level staff.",
    label: "Actionable",
    country: "Sweden",
    category: "Content",
    comments_eng:
      "I would like to learn how someone who is not involved in the sustainability team can make big strides in sustainability. I would also like to know how I can do this as a junior level staff.",
    subtopic_relevance: "relevant",
    subtopic: "Employee Engagement",
  },
  {
    ID: 4,
    received: "14-02-2024",
    module: "Introduction to Artificial Intelligence",
    idea: "Introduction to Artificial Intelligence",
    description:
      "Use AI to make decisions for fire simulation. AI can be a huge bank for ideas and previously simulations with results, which can gather all previous simulations. And help us do new simulations that has not been done before. There is a lot of opportunities in fire simulations, fire technical solutions and more. ",
    label: "Both own operations and projects",
    country: "Germany",
    category: "Content",
    comments_eng:
      "Use AI to make decisions for fire simulation. AI can be a huge bank for ideas and previously simulations with results, which can gather all previous simulations. And help us do new simulations that has not been done before. There is a lot of opportunities in fire simulations, fire technical solutions and more.",
    subtopic_relevance: "relevant",
    subtopic: "AI Implementation",
  },
  {
    ID: 5,
    received: "13-02-2024",
    module: "Carbon Assessments in Ramboll Buildings",
    idea: "Carbon Assessments in Ramboll Buildings",
    description:
      "LCA and carbon assessment trainings business unit wise on a regular basis will generate more awareness and better implementation. ",
    label: null,
    country: "Sweden",
    category: "Content",
    comments_eng:
      "LCA and carbon assessment trainings business unit wise on a regular basis will generate more awareness and better implementation.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 6,
    received: "13-02-2024",
    module: "Introduction to Artificial Intelligence",
    idea: "Introduction to Artificial Intelligence",
    description: "Monthly newsletters regarding AI implementation in Ramboll",
    label: null,
    country: "Finland",
    category: "Content",
    comments_eng: "Monthly newsletters regarding AI implementation in Ramboll",
    subtopic_relevance: "relevant",
    subtopic: "AI Implementation",
  },
  {
    ID: 7,
    received: "12-02-2024",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description:
      "Ramboll is taking great steps to incorporate sustainability while accounting for different projects, their employee and for providing solution to clients. More articles should be published in sustainability domain coming from the employee based on their projects experience. ",
    label: "Employees",
    country: "Sweden",
    category: "Content",
    comments_eng:
      "Ramboll is taking great steps to incorporate sustainability while accounting for different projects, their employee and for providing solution to clients. More articles should be published in sustainability domain coming from the employee based on their projects experience.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 8,
    received: "11-02-2024",
    module: "Dashboard",
    idea: "Dashboard",
    description:
      " I would like to propose the implementation of an Annual Virtual Employee Meeting for our team at Ramboll. Given the dynamic nature of our work environment and the increasing importance of remote collaboration, I believe this initiative will prove invaluable in keeping our workforce informed, engaged, and connected.\r\n\r\nThe Annual Virtual Employee Meeting will serve as a platform for disseminating important updates, sharing key achievements, and fostering a sense of unity and shared purpose among our employees. This meeting will provide an opportunity for our team members to participate from the comfort of their homes via Microsoft Teams, ensuring maximum accessibility and convenience for all.",
    label: null,
    country: "Germany",
    category: "Content",
    comments_eng:
      "I would like to propose the implementation of an Annual Virtual Employee Meeting for our team at Ramboll. Given the dynamic nature of our work environment and the increasing importance of remote collaboration, I believe this initiative will prove invaluable in keeping our workforce informed, engaged, and connected.\r\n\r\nThe Annual Virtual Employee Meeting will serve as a platform for disseminating important updates, sharing key achievements, and fostering a sense of unity and shared purpose among our employees. This meeting will provide an opportunity for our team members to participate from the comfort of their homes via Microsoft Teams, ensuring maximum accessibility and convenience for all.",
    subtopic_relevance: "relevant",
    subtopic: "Employee Engagement",
  },
  {
    ID: 9,
    received: "10-02-2024",
    module: "Decarbonising for net zero",
    idea: "Decarbonising for net zero",
    description:
      'Would be interesting to see the 2024-version of the scheme "% Emissions Related to Ramboll\'s Absolute Targets (from 2019)" presented in this module. ',
    label: null,
    country: "Germany",
    category: "Content",
    comments_eng:
      'translated from English:\r\nWould be interesting to see the 2024-version of the scheme "% Emissions Related to Ramboll\'s Absolute Targets (from 2019)" presented in this module.',
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 10,
    received: "09-02-2024",
    module: "Carbon Assessments in Ramboll Buildings",
    idea: "Carbon Assessments in Ramboll Buildings",
    description:
      "How the table can show that the building systems are responsible only for 0-1 % of embodied carbon? The reality in Nordics is completely different, from 20 to 50 %. \r\nIn the beginning different GHGs it might be good to tell that for example methane breaks in atmosphere to CO2. \r\nCCUS could be told to be both Carbon Capture and Utilisation or Storage, not only storage",
    label: null,
    country: "Germany",
    category: "Content",
    comments_eng:
      "translated from English: How the table can show that the building systems are responsible only for 0-1 % of embodied carbon? The reality in Nordics is completely different, from 20 to 50 %. \r\nIn the beginning different GHGs it might be good to tell that for example methane breaks in atmosphere to CO2. \r\nCCUS could be told to be both Carbon Capture and Utilisation or Storage, not only storage",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 11,
    received: "09-02-2024",
    module: "Human rights and sustainability",
    idea: "Human rights and sustainability",
    description:
      "I'm curious to know in what stage should Ramboll ask about Client's approach and policies on maintaining human rights and when is the good time to walk away from a tender if we find out about a violation of the human rights in the client's end?",
    label: null,
    country: "Germany",
    category: "Content",
    comments_eng:
      "I'm curious to know in what stage should Ramboll ask about Client's approach and policies on maintaining human rights and when is the good time to walk away from a tender if we find out about a violation of the human rights in the client's end?",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 12,
    received: "09-02-2024",
    module: "Environmental commitments and actions in Ramboll",
    idea: "Environmental commitments and actions in Ramboll",
    description:
      "I feel the difficulty applying this approach to Ramboll Japan since the Japan is so behind about decarbonization and especially about the awareness of reduction of plastics.",
    label: null,
    country: "Denmark",
    category: "Content",
    comments_eng:
      "translated from English: I feel the difficulty applying this approach to Ramboll Japan since the Japan is so behind about decarbonization and especially about the awareness of reduction of plastics.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 13,
    received: "09-02-2024",
    module: "Speaking to clients about sustainability",
    idea: "Speaking to clients about sustainability",
    description:
      "I do not feel any connection between our team's daily activities and the corporate sustainability goals. Does the top management involve the intermediate managers in the sustainability actions?",
    label: null,
    country: "Denmark",
    category: "Content",
    comments_eng:
      "I do not feel any connection between our team's daily activities and the corporate sustainability goals. Does the top management involve the intermediate managers in the sustainability actions?",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 14,
    received: "07-02-2024",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description:
      "Sustainability is the only way forward and I am happy being part of a company that doe not just believe this, but shows it in its projects and day to day activities.",
    label: null,
    country: "Denmark",
    category: "Content",
    comments_eng:
      "Sustainability is the only way forward and I am happy being part of a company that does not just believe this, but shows it in its projects and day to day activities.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 15,
    received: "04-02-2024",
    module: "Introduction to CSRD",
    idea: "Introduction to CSRD",
    description:
      "A video summary of the annual results or a townhall with the annual results will help in understanding the annual report and the sustainability initiatives better",
    label: null,
    country: "Finland",
    category: "Content",
    comments_eng:
      "A video summary of the annual results or a townhall with the annual results will help in understanding the annual report and the sustainability initiatives better",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 16,
    received: "31-01-2024",
    module: "Decarbonising for net zero",
    idea: "Decarbonising for net zero",
    description:
      'Help with knowledge sharing of sustainable solutions for classical engineering disciplines like "what is sustainable electronics" and sustainable alternative (to)steel materials, where both strength, lifetime and technical requirements has to be comparable to existing industrial stanadrs',
    label: null,
    country: "Sweden",
    category: "Content",
    comments_eng:
      'Help with knowledge sharing of sustainable solutions for classical engineering disciplines like "what is sustainable electronics" and sustainable alternative (to)steel materials, where both strength, lifetime and technical requirements has to be comparable to existing industrial stanadrs.',
    subtopic_relevance: "relevant",
    subtopic: "Knowledge Sharing",
  },
  {
    ID: 17,
    received: "29-01-2024",
    module: "Sustainability in Ramboll's business strategy",
    idea: "Sustainability in Ramboll's business strategy",
    description:
      "Is always important to understanding Sustainability Fundamentals.",
    label: null,
    country: "Germany",
    category: "Content",
    comments_eng:
      "Is always important to understanding Sustainability Fundamentals.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 18,
    received: "29-01-2024",
    module: "Sustainability in Ramboll's business strategy",
    idea: "Sustainability in Ramboll's business strategy",
    description:
      "Is always important to Understanding Sustainability Fundamentals.",
    label: null,
    country: "Denmark",
    category: "Content",
    comments_eng:
      "Is always important to Understanding Sustainability Fundamentals.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 19,
    received: "17-01-2024",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description:
      "decarbonizing for net zero and by creating resilient society.",
    label: "Training",
    country: "Sweden",
    category: "Content",
    comments_eng:
      "translated from English: decarbonizing for net zero and by creating resilient society.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 20,
    received: "17-01-2024",
    module: "Carbon Reduction in Ramboll Buildings",
    idea: "Carbon Reduction in Ramboll Buildings",
    description: "Informative",
    label: null,
    country: "Germany",
    category: "Content",
    comments_eng: "Informative",
    subtopic_relevance: "not related",
    subtopic: null,
  },
  {
    ID: 21,
    received: "16-01-2024",
    module: "The EU Taxonomy and what it means for Ramboll",
    idea: "The EU Taxonomy and what it means for Ramboll",
    description: "Very interesting issue and a lot of opportunities in Spain ",
    label: null,
    country: "Denmark",
    category: "Content",
    comments_eng: "Very interesting issue and a lot of opportunities in Spain",
    subtopic_relevance: "relevant",
    subtopic: "Opportunities in Spain",
  },
  {
    ID: 22,
    received: "15-01-2024",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description:
      "Hvordan organiserer vi os internt ift. at kunne skabe holistiske, bæredygtige løsninger for vores kunder? Og hvordan får vi fortalt internt og eksternt om vores arbejde med bæredygtighed på projekterne. ",
    label: "Communication",
    country: "Germany",
    category: "Content",
    comments_eng:
      "translated from Danish: How do we organize ourselves internally in order to create holistic, sustainable solutions for our customers? And how do we communicate internally and externally about our work on sustainability in the projects.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 23,
    received: "11-01-2024",
    module: "Introduction to Artificial Intelligence",
    idea: "Introduction to Artificial Intelligence",
    description:
      "I need to review the information for the Centre of Intelligence and GRT.",
    label: null,
    country: "Sweden",
    category: "Content",
    comments_eng:
      "I need to review the information for the Centre of Intelligence and GRT.",
    subtopic_relevance: "relevant",
    subtopic: "Knowledge Sharing",
  },
  {
    ID: 24,
    received: "11-01-2024",
    module: "Sustainability in the project model",
    idea: "Sustainability in the project model",
    description: "Yritän sisäistää kestävää kehitystä.",
    label: null,
    country: "Germany",
    category: "Content",
    comments_eng:
      "translated from Finnish: I'm trying to internalize sustainable development.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 25,
    received: "11-01-2024",
    module: "Sustainability in Ramboll's business strategy",
    idea: "Sustainability in Ramboll's business strategy",
    description:
      "Tässä ollaan vasta ensimmäisiä päiviä Rambollilla niin vielä ei ole kestävän kehityksen tilanne selvillä.",
    label: null,
    country: "Sweden",
    category: "Content",
    comments_eng:
      'translated from Finnish: "Here we are only in the first few days at Ramboll, so the state of sustainable development is not yet clear."',
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 26,
    received: "11-01-2024",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description:
      "Tärkeintä tässä on tilaajan konsultointi ja ajatusten myyminen, muutoin ei päästä suunnittelemaan kestävästi.",
    label: null,
    country: "Sweden",
    category: "Content",
    comments_eng:
      "translated from Finnish: The most important thing here is consulting the client and selling ideas, otherwise sustainable planning cannot be achieved.",
    subtopic_relevance: "relevant",
    subtopic: "Consulting and selling ideas to the client",
  },
  {
    ID: 27,
    received: "10-01-2024",
    module: "Sustainability in Ramboll's business strategy",
    idea: "Sustainability in Ramboll's business strategy",
    description:
      "Look forward to learning specific module for each unifying theme",
    label: null,
    country: "Finland",
    category: "Content",
    comments_eng:
      "Look forward to learning specific module for each unifying theme",
    subtopic_relevance: "relevant",
    subtopic: "Project-Based Learning",
  },
  {
    ID: 28,
    received: "09-01-2024",
    module: "Sustainability in Ramboll's business strategy",
    idea: "Sustainability in Ramboll's business strategy",
    description:
      "I'm happy to work towards sustainable change. I think it's a right path for the company but I'm wondering how this impact my role as financial project assistant?",
    label: "Employees",
    country: "Denmark",
    category: "Content",
    comments_eng:
      "I'm happy to work towards sustainable change. I think it's a right path for the company but I'm wondering how this impact my role as financial project assistant?",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 29,
    received: "08-01-2024",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description: "Continued learning and how it applies to all departments",
    label: "Unsure",
    country: "Denmark",
    category: "Content",
    comments_eng: "Continued learning and how it applies to all departments",
    subtopic_relevance: "relevant",
    subtopic: "Employee Engagement",
  },
  {
    ID: 30,
    received: "08-01-2024",
    module: "Sustainability in Ramboll's business strategy",
    idea: "Sustainability in Ramboll's business strategy",
    description:
      "Each project that Ramboll undertakes can perhaps have completion brief highlighting how the any of the 4 sustainability themes were applied or perhaps a novel way that sustainability was promoted in the project to inspire others to use in future projects.",
    label: "Both own operations and projects",
    country: "Sweden",
    category: "Content",
    comments_eng:
      "Each project that Ramboll undertakes can perhaps have completion brief highlighting how the any of the 4 sustainability themes were applied or perhaps a novel way that sustainability was promoted in the project to inspire others to use in future projects.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 31,
    received: "08-01-2024",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description:
      "we have a challenge in convincing many clients to commence the sustainability journey",
    label: null,
    country: "Finland",
    category: "Content",
    comments_eng:
      "we have a challenge in convincing many clients to commence the sustainability journey",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 32,
    received: "08-01-2024",
    module: "Speaking to clients about sustainability",
    idea: "Speaking to clients about sustainability",
    description: "Kohdennetaan koulutukset paremmin eri ammattiryhmille.",
    label: null,
    country: "Finland",
    category: "Content",
    comments_eng:
      "translated from Finnish: Let's target the trainings better for different professional groups.",
    subtopic_relevance: "relevant",
    subtopic: "Employee Engagement",
  },
  {
    ID: 33,
    received: "05-01-2024",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description:
      "The engineering I work in sometimes dates from the 19th century and mostly through practical engineering reasons (occasionally cost), the infrastructure owners sometimes need to maintain this old equipment. However sometimes, using, producing and transporting new equipment may cause more problems with emissions to the environment than maintaining the older equipment.",
    label: "Ressource management and circular economy",
    country: "Sweden",
    category: "Content",
    comments_eng:
      "The engineering I work in sometimes dates from the 19th century and mostly through practical engineering reasons (occasionally cost), the infrastructure owners sometimes need to maintain this old equipment. However sometimes, using, producing and transporting new equipment may cause more problems with emissions to the environment than maintaining the older equipment.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 34,
    received: "02-01-2024",
    module: "Sustainability in Ramboll's business strategy",
    idea: "Sustainability in Ramboll's business strategy",
    description:
      "Business enablement is not always shown in the sustainability examples on the training or well represented when showcasing progress within Ramboll.",
    label: "Own Operations: Communication",
    country: "Denmark",
    category: "Content",
    comments_eng:
      "Business enablement is not always shown in the sustainability examples on the training or well represented when showcasing progress within Ramboll.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 35,
    received: "29-12-2023",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description:
      "Enemmän valmiita työkaluja joita käyttää päivittäisessä suunnittelussa. ",
    label: "Tools",
    country: "Germany",
    category: "Content",
    comments_eng:
      "translated from Finnish: More ready-made tools to use in daily planning.",
    subtopic_relevance: "relevant",
    subtopic: "Project-Based Learning",
  },
  {
    ID: 36,
    received: "29-12-2023",
    module: "Sustainability in Ramboll's business strategy",
    idea: "Sustainability in Ramboll's business strategy",
    description:
      "Yleisen koulutustarjonnan lisäksi tekniikka-aloille olisi hyvä saada jotain räätälöityä. Esim. työryhmäpohdintaa mahdollisesti kokeneen sparraajan kanssa.",
    label: "Own Operations: Employees",
    country: "Denmark",
    category: "Content",
    comments_eng:
      "translated from Finnish: In addition to general education offerings, it would be good to have something tailored for the technology fields. For example, group discussions possibly with an experienced coach.",
    subtopic_relevance: "relevant",
    subtopic: "Knowledge Sharing",
  },
  {
    ID: 37,
    received: "28-12-2023",
    module: "Speaking to clients about sustainability",
    idea: "Speaking to clients about sustainability",
    description:
      "It's important to talk regularly about sustainability and good examples that are relevant for us and our clients so that everyone are updated and feel comfortable with it.",
    label: "Tools: Examples",
    country: "Finland",
    category: "Content",
    comments_eng:
      "It's important to talk regularly about sustainability and good examples that are relevant for us and our clients so that everyone are updated and feel comfortable with it.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 38,
    received: "26-12-2023",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description:
      'I would like to see "Sustainability" itself clearly defined. ',
    label: null,
    country: "Germany",
    category: "Content",
    comments_eng:
      'I would like to see "Sustainability" itself clearly defined.',
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 39,
    received: "22-12-2023",
    module: "Sustainability in Ramboll's business strategy",
    idea: "Sustainability in Ramboll's business strategy",
    description:
      "Add a info to explain or teach about tipping points. Biodiversity and ecosystems go hand to hand with tipping points.",
    label: "Biodiversity and ecosystem",
    country: "Denmark",
    category: "Content",
    comments_eng:
      "Add a info to explain or teach about tipping points. Biodiversity and ecosystems go hand to hand with tipping points.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 40,
    received: "21-12-2023",
    module: "The EU Taxonomy and what it means for Ramboll",
    idea: "The EU Taxonomy and what it means for Ramboll",
    description: "Needs to be a prt of sustainability workshops for a project",
    label: null,
    country: "Germany",
    category: "Content",
    comments_eng:
      "Needs to be a part of sustainability workshops for a project",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 41,
    received: "21-12-2023",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description:
      "More case studies that relate to projects and business development.",
    label: null,
    country: "Germany",
    category: "Content",
    comments_eng:
      "More case studies that relate to projects and business development.",
    subtopic_relevance: "relevant",
    subtopic: "Project-Based Learning",
  },
  {
    ID: 42,
    received: "20-12-2023",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description:
      " sustainable practices in day-to-day work activities \r\n\r\nMinimizing time and energy spent on the road  is  an integral part.\r\n",
    label: "Own Operations: Employees",
    country: "Finland",
    category: "Content",
    comments_eng:
      "sustainable practices in day-to-day work activities \r\n\r\nMinimizing time and energy spent on the road  is  an integral part.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 43,
    received: "20-12-2023",
    module: "Sustainability in Ramboll's business strategy",
    idea: "Sustainability in Ramboll's business strategy",
    description:
      "Would like to have more information on further exposure to some of these trainings to position myself better.",
    label: null,
    country: "Finland",
    category: "Content",
    comments_eng:
      "Would like to have more information on further exposure to some of these trainings to position myself better.",
    subtopic_relevance: "relevant",
    subtopic: "Employee Engagement",
  },
  {
    ID: 44,
    received: "19-12-2023",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description:
      "better understanding of the SURE sustainability tool and more learning modules and how to apply to site solutions activates  ",
    label: "Own Operations: Employees",
    country: "Sweden",
    category: "Content",
    comments_eng:
      "better understanding of the SURE sustainability tool and more learning modules and how to apply to site solutions activates",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 45,
    received: "19-12-2023",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description: "I  like to improve more sustainability towards environment ",
    label: null,
    country: "Finland",
    category: "Content",
    comments_eng: "I like to improve more sustainability towards environment",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 46,
    received: "19-12-2023",
    module: "Speaking to clients about sustainability",
    idea: "Speaking to clients about sustainability",
    description:
      "En ole projektipäällikkö, en tee asiakaskyselyitä enkä ole kontaktissa heidän kanssaan näihin liityen. Suuri osa koulutuksesta on suunnattu pp:lle ja projektinjohtajille.",
    label: "Training: No Category",
    country: "Germany",
    category: "Content",
    comments_eng:
      "translated from Finnish: I am not a project manager, I do not conduct customer surveys, and I am not in contact with them regarding these matters. A large part of the training is aimed at project managers and project managers.",
    subtopic_relevance: "not related",
    subtopic: null,
  },
  {
    ID: 47,
    received: "18-12-2023",
    module: "Sustainability in Ramboll's business strategy",
    idea: "Sustainability in Ramboll's business strategy",
    description: "Love the development in sustainability within Ramboll.",
    label: null,
    country: "Denmark",
    category: "Content",
    comments_eng: "Love the development in sustainability within Ramboll.",
    subtopic_relevance: "relevant",
    subtopic: "Sustainability Awareness",
  },
  {
    ID: 48,
    received: "18-12-2023",
    module: "Decarbonising for net zero",
    idea: "Decarbonising for net zero",
    description: "By Providing some trainings",
    label: "Training",
    country: "Sweden",
    category: "Content",
    comments_eng: "By Providing some trainings",
    subtopic_relevance: "relevant",
    subtopic: "Employee Engagement",
  },
  {
    ID: 49,
    received: "18-12-2023",
    module: "Sustainability in Ramboll's business strategy",
    idea: "Sustainability in Ramboll's business strategy",
    description:
      "Smaller or niche departments may required different type of support ",
    label: "Training",
    country: "Germany",
    category: "Content",
    comments_eng:
      "Smaller or niche departments may required different type of support",
    subtopic_relevance: "relevant",
    subtopic: "Employee Engagement",
  },
  {
    ID: 50,
    received: "15-12-2023",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description: "Kompakti esitys",
    label: null,
    country: "Sweden",
    category: "Content",
    comments_eng: "translated from Finnish: Compact presentation",
    subtopic_relevance: "not related",
    subtopic: null,
  },
  {
    ID: 51,
    received: "15-12-2023",
    module: "Decarbonising for net zero",
    idea: "Decarbonising for net zero",
    description:
      "The modules are great. However, we should have actual examples of the decarbonisation from projects. Moreover, we should have more examples what the actual pain points of the client in terms of sustainability and solutions how we can tackle them.",
    label: "Strategy",
    country: "Denmark",
    category: "Content",
    comments_eng:
      "The modules are great. However, we should have actual examples of the decarbonisation from projects. Moreover, we should have more examples what the actual pain points of the client in terms of sustainability and solutions how we can tackle them.",
    subtopic_relevance: "relevant",
    subtopic: "Project-Based Learning",
  },
  {
    ID: 52,
    received: "15-12-2023",
    module: "Introduction to sustainability in Ramboll",
    idea: "Introduction to sustainability in Ramboll",
    description:
      "It would be good to have a short talk/interview/podcast with project managers/project staff on how they have integrated sustainability in their projects.",
    label: null,
    country: "Sweden",
    category: "Content",
    comments_eng:
      "It would be good to have a short talk/interview/podcast with project managers/project staff on how they have integrated sustainability in their projects.",
    subtopic_relevance: "relevant",
    subtopic: "Knowledge Sharing",
  },
];
